import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [message, setMessage] = useState('');
  const [postMessage, setPostMessage] = useState('');
  const [customMessage, setCustomMessage] = useState('');

  const sendMessageToExtension = () => {
    window.postMessage(
      {
        source: 'my-nextjs-app',
        data: postMessage,
      },
      '*'
    );
    window.postMessage(
      {
        source: 'test-app',
        data: postMessage,
      },
      '*'
    );
  };
  // const sendMessageToExtension = () => {
  //   const event = new CustomEvent('my-nextjs-app-event', { detail: 'Hello, Chrome Extension' });
  //   window.dispatchEvent(event);
  // };

  
  useEffect(() => {
    const handleMessage = (event:any, b, c, d) => {
      console.log(event,b,c,d);
      if (event.source !== window) return;
      if (event.data.source && event.data.source === 'my-chrome-extension') {
        setMessage(event.data.data);
      } else if (event.data.source && event.data.source === 'my-nextjs-app') {
        console.log('native', event.data.data);
      } else if (event.data.source && event.data.source === 'post-app') {
        console.log('post', event.data.data);
        setCustomMessage(event.data.data);
      } else if (event.data.source && event.data.source === 'test-app') {
        console.log('test', event.data.data);
      }
    };

    window.addEventListener('message', handleMessage);

    return () => {
      window.removeEventListener('message', handleMessage);
    };
  }, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>
        <div className={styles.description}>
          <p>{message || 'No message received yet.'}</p>
          <div>
            <input
              type="text"
              value={postMessage}
              onChange={(e) => setPostMessage(e.target.value)}
            />
            {' '}
            <button onClick={sendMessageToExtension}>
              Send Message to Chrome Extension
            </button>
          </div>
          <div>
            {customMessage}
          </div>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
